pipeline {
      agent { node { label 'aws-ec2' } }

    parameters {
        string(name: 'REGION', defaultValue: 'us-east-1', description: 'AWS Region')
        string(name: 'CLUSTER_NAME', defaultValue: 'demo-eks', description: 'EKS Cluster Name to Delete')
    }


    stages {

        stage('Install unzip (if missing)') {
            steps {
                sh '''
                    if ! command -v unzip &> /dev/null; then
                        echo "Installing unzip..."
                        sudo apt-get update -y
                        sudo apt-get install -y unzip
                    else
                        echo "unzip already installed"
                    fi
                '''
            }
        }

        stage('Install AWS CLI (if missing)') {
            steps {
                sh '''
                    if ! command -v aws &> /dev/null; then
                        echo "Installing AWS CLI..."
                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                        unzip -o awscliv2.zip
                        sudo ./aws/install  --update
                    else
                        echo "AWS CLI already installed"
                    fi
                    aws --version
                '''
            }
        }

        stage('Setup AWS CLI Credentials') {
            steps {
                withCredentials([
                    usernamePassword(credentialsId: 'CNCF_EKS_ACCESS_KEY', usernameVariable: 's3_access_key', passwordVariable: 's3_secret_key'),
                ]){
                sh """
                    mkdir -p ~/.aws
                    cat > ~/.aws/credentials <<EOF
[default]
aws_access_key_id = ${s3_access_key}
aws_secret_access_key = ${s3_secret_key}
EOF

                    cat > ~/.aws/config <<EOF
[default]
region = ${params.REGION}
output = json
EOF
                """
                }
            }
        }

        stage('Install eksctl (if missing)') {
            steps {
                sh '''
                    if ! command -v eksctl &> /dev/null; then
                        echo "Installing eksctl..."
                        curl -L "https://github.com/eksctl-io/eksctl/releases/download/v0.215.0/eksctl_Linux_amd64.tar.gz" -o eksctl.tar.gz
                        tar -xzf eksctl.tar.gz
                        sudo mv eksctl /usr/local/bin/
                    else
                        echo "eksctl already installed"
                    fi
                    eksctl version
                '''
            }
        }

        stage('Delete EKS Cluster') {
            steps {
                echo "Preparing to delete EKS cluster: ${params.CLUSTER_NAME} in region: ${params.REGION}"
                sh '''
                    echo "Deleting EKS cluster ${CLUSTER_NAME}..."
                    eksctl delete cluster --name ${CLUSTER_NAME} --region ${REGION} --wait
                '''
            }
        }
    }

    post {
        always {
            echo "Cluster deletion process completed."
        }
    }
}
