pipeline {

  agent { node { label 'aws-ec2' } }

      parameters {
        string(name: 'SIZE', defaultValue: 'ci', description: 'The size need to test, it should be medium, small or ci')
        string(name: 'VUS', defaultValue: '100', description: 'The number of virtual users to simulate')
        string(name: 'INGRESS_IP', defaultValue: '145.40.81.171', description: 'The ingress IP address')
        string(name: 'PERF_REPO', defaultValue: 'https://github.com/goharbor/perf.git', description: 'The performance test repository')
        string(name: 'PERF_REPO_BRANCH', defaultValue: 'main', description: 'The performance test branch to use')
        booleanParam(name: 'auto_sbom_generation', defaultValue: false, description: 'Whether to enable auto generate sbom')
        string(name: 'fake_scanner_url', defaultValue: 'https://fake-scanner.domain', description: 'The fake scanner url to use')
        string(name: 'recipient', defaultValue: 'stone.zhang@broadcom.com', description: 'The email address to send notifications to')
    }

    environment {
        PREPARE="$prepare"
        HARBOR_SIZE="${params.SIZE}"
        HARBOR_VUS="${params.VUS}"
        INGRESSIP="${params.INGRESS_IP}"
        HARBOR_URL="https://admin:Harbor12345@core.harbor.domain"
        HARBOR_REPORT="true"
        KUBECONFIG="/var/lib/jenkins/.kube/config"
        GOROOT="/root/go1.25"
        PATH="$GOROOT/bin:$PATH"
    }

    stages {

        stage('install dependencies') {
            steps {
                sh """
                    sudo apt-get update -y
                    sudo apt-get install -y zip
                """
            }
        }

        stage('mapping hostname in /etc/hosts') {
            steps {
                sh """
                    if ! grep -q "core.harbor.domain" /etc/hosts; then
                        echo "Mapping hostname to /etc/hosts"
                        echo "${params.INGRESS_IP} core.harbor.domain" | sudo tee -a /etc/hosts
                    else
                        echo "Hostname already mapped in /etc/hosts, replacing it"
                        sudo sed -i.bak "/core.harbor.domain/c\\${params.INGRESS_IP} core.harbor.domain" /etc/hosts
                    fi
                """
            }
        }

        stage('Prepare Data') {
            steps {
                sh """
                    rm -rf perf && git clone "${params.PERF_REPO}" && cd perf && git checkout "${params.PERF_REPO_BRANCH}"
                    AUTO_SBOM_GENERATION="$auto_sbom_generation" FAKE_SCANNER_URL="$fake_scanner_url" go run mage.go prepare
                """
            }
        }

        stage('Performance Test') {
            steps {
                sh """
                    rm -rf perf && git clone "${params.PERF_REPO}" && cd perf && git checkout "${params.PERF_REPO_BRANCH}"
                    env
                    pwd
                    go run mage.go
                    # backup results
                    cp ./outputs/report.md /tmp/report.md
                    echo "Performance test completed. backup result file: "
                    zip -r "${JOB_NAME}-${BUILD_NUMBER}.zip" ./outputs/
                    mv "${JOB_NAME}-${BUILD_NUMBER}.zip" /var/reports/
                """


                script {
                    sh 'cp /tmp/report.md report.md'
                }
            }
        }
    }
    post {
        success {
            echo 'The build was successful!'

            emailext subject: "Harbor performance on the kubernetes #${env.BUILD_NUMBER} - SUCCESS",
            body: """
                <p>Build #${env.BUILD_NUMBER} result: <strong>SUCCESS</strong></p>
                <p>View build details: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
                <p> Performance test report: <a href="${env.JOB_URL}/Trivy_20Scan_20CVE_20Report/">Performance test report</a></p>
            """,
            mimeType: 'text/html',
            to: "${params.recipient}"
        }

        failure {
            echo 'The build failed.'
            emailext subject: "Harbor performance on the kubernetes #${env.BUILD_NUMBER} - FAILED",
            body: """
                <p>Build #${env.BUILD_NUMBER} result: <strong>FAILED</strong></p>
                <p>View build details: <a href="${env.BUILD_URL}">${env.BUILD_URL}</a></p>
            """,
            mimeType: 'text/html',
            to: "${params.recipient}"
        }
    }
}